### ISSUE TITLE
Including quota_definition_guid in /billable_events is expensive

### ISSUE THREAD

**Issue by 46bit** [alphagov/paas-billing#71]
The `/billable_events` endpoint includes a `quota_definition_guid` field. That field is included by doing a `LEFT JOIN` with the `orgs` table. That seems to take >3 seconds for a large organisation. This field seems to only be actually used by hacky code in the `paas-admin` reports, and could be cheaply done by a new API endpoint.

https://github.com/alphagov/paas-billing/blob/master/eventstore/store_billable_events.go#L192-L193

**Comment by richardTowers** [comment]
This join has actually been removed to fix a separate bug - should we close this issue?

**Comment by 46bit** [comment]
The field in question was removed by https://github.com/alphagov/paas-billing/pull/75
